export const ERROR_CODES = {
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  INVALID_INPUT: 'INVALID_INPUT',
  QUERY_FAILED: 'QUERY_FAILED',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
